In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from google.colab import files
uploaded = files.upload()

Saving 77_cancer_proteomes_CPTAC_itraq.csv to 77_cancer_proteomes_CPTAC_itraq.csv

In [8]:
df = pd.read_csv('/content/77_cancer_proteomes_CPTAC_itraq.csv')

In [9]:
df.head()

,RefSeq_accession_number,gene_symbol,gene_name,AO-A12D.01TCGA,C8-A131.01TCGA,AO-A12B.01TCGA,BH-A18Q.02TCGA,C8-A130.02TCGA,C8-A138.03TCGA,E2-A154.03TCGA,...,AO-A12B.34TCGA,A2-A0SW.35TCGA,AO-A0JL.35TCGA,BH-A0BV.35TCGA,A2-A0YM.36TCGA,BH-A0C7.36TCGA,A2-A0SX.36TCGA,263d3f-I.CPTAC,blcdb9-I.CPTAC,c4155b-C.CPTAC
0,NP_958782,PLEC,plectin isoform 1,1.096131,2.609943,-0.659828,0.195341,-0.494060,2.765081,0.862659,...,-0.963904,-0.487772,-0.10668,-0.065838,0.655850,-0.552212,-0.398560,0.598585,-0.191285,0.566975
1,NP_958785,NaN,plectin isoform 1g,1.111370,2.650422,-0.648742,0.215413,-0.503899,2.779709,0.870186,...,-0.938210,-0.487772,-0.10668,-0.055893,0.658143,-0.547749,-0.392601,0.606697,-0.183918,0.578702
2,NP_958786,PLEC,plectin isoform 1a,1.111370,2.650422,-0.654285,0.215413,-0.500619,2.779709,0.870186,...,-0.943919,-0.487772,-0.10668,-0.065838,0.655850,-0.552212,-0.392601,0.603993,-0.186022,0.576747
3,NP_000436,NaN,plectin isoform 1c,1.107561,2.646374,-0.632113,0.205377,-0.510459,2.797995,0.866423,...,-0.935355,-0.487772,-0.10668,-0.055893,0.655850,-0.552212,-0.392601,0.603993,-0.186022,0.576747
4,NP_958781,NaN,plectin isoform 1e,1.115180,2.646374,-0.640428,0.215413,-0.503899,2.787023,0.870186,...,-0.935355,-0.503853,-0.10668,-0.062523,0.651264,-0.556675,-0.395581,0.603993,-0.167079,0.576747

In [10]:
df.isnull()

,RefSeq_accession_number,gene_symbol,gene_name,AO-A12D.01TCGA,C8-A131.01TCGA,AO-A12B.01TCGA,BH-A18Q.02TCGA,C8-A130.02TCGA,C8-A138.03TCGA,E2-A154.03TCGA,...,AO-A12B.34TCGA,A2-A0SW.35TCGA,AO-A0JL.35TCGA,BH-A0BV.35TCGA,A2-A0YM.36TCGA,BH-A0C7.36TCGA,A2-A0SX.36TCGA,263d3f-I.CPTAC,blcdb9-I.CPTAC,c4155b-C.CPTAC
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12548,False,True,False,True,True,True,False,False,False,False,...,False,True,True,True,True,True,True,False,False,False
12549,False,True,False,True,True,True,False,False,False,False,...,True,True,True,True,True,True,True,False,False,False
12550,False,False,False,True,True,True,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
12551,False,False,False,False,False,False,True,True,True,True,...,True,True,True,True,True,True,True,False,False,False
12552,False,False,False,False,False,False,False,False,True,True,...,False,True,True,True,True,True,True,True,True,True

In [11]:
df.isnull().sum()

RefSeq_accession_number       0
gene_symbol                1780
gene_name                     0
AO-A12D.01TCGA             1219
C8-A131.01TCGA             1218
                           ...
BH-A0C7.36TCGA             2860
A2-A0SX.36TCGA             2856
263d3f-I.CPTAC             1641
blcdb9-I.CPTAC             1668
c4155b-C.CPTAC             1640
Length: 86, dtype: int64

In [12]:
df.describe()

,AO-A12D.01TCGA,C8-A131.01TCGA,AO-A12B.01TCGA,BH-A18Q.02TCGA,C8-A130.02TCGA,C8-A138.03TCGA,E2-A154.03TCGA,C8-A12L.04TCGA,A2-A0EX.04TCGA,AO-A12D.05TCGA,...,AO-A12B.34TCGA,A2-A0SW.35TCGA,AO-A0JL.35TCGA,BH-A0BV.35TCGA,A2-A0YM.36TCGA,BH-A0C7.36TCGA,A2-A0SX.36TCGA,263d3f-I.CPTAC,blcdb9-I.CPTAC,c4155b-C.CPTAC
count,11334.000000,11335.000000,11334.000000,12024.000000,12025.000000,11833.000000,11833.000000,11732.000000,11732.000000,11276.000000,...,11477.000000,10324.000000,10324.000000,10324.000000,9694.000000,9693.000000,9697.000000,10912.000000,10885.000000,10913.000000
mean,0.133079,0.128822,-0.440764,-0.729233,-0.039436,0.115353,-0.618354,-0.305320,-0.021228,0.077247,...,-0.677085,-0.103215,-0.021222,-0.100912,0.488502,-0.368762,-0.050669,0.069555,-0.298170,0.310974
std,1.734231,1.579845,1.634930,2.422452,1.353505,1.652918,2.281818,1.567687,1.651917,1.749695,...,2.018394,1.570606,1.656519,1.628017,1.658080,1.453737,1.716237,1.950822,1.307027,1.706759
min,-12.466750,-13.156553,-9.911008,-24.553794,-15.004199,-12.956961,-16.640848,-18.710032,-14.711526,-13.441463,...,-12.497832,-12.152747,-11.874381,-11.128835,-8.772601,-10.427946,-12.967849,-12.609296,-9.058864,-6.328154
25%,-0.656376,-0.583835,-1.330525,-1.266591,-0.671172,-0.679944,-1.278707,-0.991299,-0.718023,-0.728075,...,-1.731881,-0.815820,-0.740905,-0.805968,-0.497485,-1.063180,-0.934818,-0.867155,-1.056363,-0.652571
50%,0.078915,0.116448,-0.318937,-0.296430,0.024160,0.088055,-0.157218,-0.231885,0.037039,0.045209,...,-0.444306,-0.056808,0.023619,-0.037659,0.314206,-0.204129,-0.079784,0.052313,-0.191285,0.137007
75%,0.905641,0.853163,0.489641,0.449590,0.719492,0.929197,0.670727,0.483663,0.750830,0.862472,...,0.500677,0.657177,0.800701,0.714075,1.276655,0.521043,0.757374,1.009641,0.574868,1.059485
max,17.623036,12.677023,8.289261,11.790434,6.925004,10.602330,10.079191,8.804312,9.548006,13.066445,...,8.839935,10.694780,11.309371,12.638208,11.164262,7.886564,11.521261,16.183559,6.435721,10.497291

In [13]:
df.shape

(12553, 86)

In [14]:
df.drop(columns=["RefSeq_accession_number"], inplace=True)

In [15]:
df.drop(columns=["gene_name"], inplace=True)

In [16]:
cat_cols = df.select_dtypes(include=["object"]).columns

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [17]:
num_cols = df.select_dtypes(include=[np.number]).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
print(df.isnull().sum().sum())
print(df.shape)

0
(12548, 84)

In [20]:
threshold = len(df) * 0.5

df = df.dropna(axis=1, thresh=threshold)

print(df.shape)

(12548, 84)

In [21]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [23]:
df = pd.get_dummies(df, drop_first=True)

In [24]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)

In [25]:
kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

kmeans.fit(X_scaled)

print("K-Means Model Trained Successfully!")

K-Means Model Trained Successfully!

In [26]:
df["Cluster"] = kmeans.labels_

print(df.head())

   AO-A12D.01TCGA  C8-A131.01TCGA  AO-A12B.01TCGA  BH-A18Q.02TCGA  \
0        1.096131        2.609943       -0.659828        0.195341
1        1.111370        2.650422       -0.648742        0.215413
2        1.111370        2.650422       -0.654285        0.215413
3        1.107561        2.646374       -0.632113        0.205377
4        1.115180        2.646374       -0.640428        0.215413

   C8-A130.02TCGA  C8-A138.03TCGA  E2-A154.03TCGA  C8-A12L.04TCGA  \
0       -0.494060        2.765081        0.862659        1.407570
1       -0.503899        2.779709        0.870186        1.407570
2       -0.500619        2.779709        0.870186        1.410312
3       -0.510459        2.797995        0.866423        1.407570
4       -0.503899        2.787023        0.870186        1.413053

   A2-A0EX.04TCGA  AO-A12D.05TCGA  ...  gene_symbol_ZSCAN29  gene_symbol_ZW10  \
0        1.185108        1.100688  ...                False             False
1        1.192612        1.100688  ...                False             False
2        1.188860        1.100688  ...                False             False
3        1.185108        1.100688  ...                False             False
4        1.200116        1.093358  ...                False             False

   gene_symbol_ZWILCH  gene_symbol_ZWINT  gene_symbol_ZYG11A  \
0               False              False               False
1               False              False               False
2               False              False               False
3               False              False               False
4               False              False               False

   gene_symbol_ZYG11B  gene_symbol_ZYX  gene_symbol_ZZEF1  gene_symbol_ZZZ3  \
0               False            False              False             False
1               False            False              False             False
2               False            False              False             False
3               False            False              False             False
4               False            False              False             False

   Cluster
0        0
1        0
2        0
3        0
4        0

[5 rows x 10145 columns]

In [29]:
from sklearn.metrics import calinski_harabasz_score, davies_bouldin_score

print("Calinski-Harabasz Score:",
      calinski_harabasz_score(X_scaled, kmeans.labels_))

print("Davies-Bouldin Score:",
      davies_bouldin_score(X_scaled, kmeans.labels_))

Calinski-Harabasz Score: 6.711179529397904
Davies-Bouldin Score: 36.79280170814402

In [30]:
from sklearn.decomposition import PCA

pca = PCA(n_components=20)
X_pca = pca.fit_transform(X_scaled)

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
kmeans.fit(X_pca)

KMeans(n_clusters=3, n_init=10, random_state=42)

In [31]:
from sklearn.metrics import (
    silhouette_score,
    calinski_harabasz_score,
    davies_bouldin_score
)

# Silhouette Score
sil_score = silhouette_score(
    X_scaled,
    kmeans.labels_,
    sample_size=2000,    # Faster for large datasets
    random_state=42
)

# Calinski-Harabasz Score
ch_score = calinski_harabasz_score(
    X_scaled,
    kmeans.labels_
)

# Davies-Bouldin Score
db_score = davies_bouldin_score(
    X_scaled,
    kmeans.labels_
)

print("========== K-Means Evaluation Metrics ==========")
print(f"Silhouette Score         : {sil_score:.4f}")
print(f"Calinski-Harabasz Score  : {ch_score:.4f}")
print(f"Davies-Bouldin Score     : {db_score:.4f}")

========== K-Means Evaluation Metrics ==========
Silhouette Score         : -0.0052
Calinski-Harabasz Score  : 6.9561
Davies-Bouldin Score     : 30.0394

In [32]:
cluster_predictions = kmeans.predict(X_pca)

print(cluster_predictions)

[0 0 0 ... 0 0 2]